[tools]
bun = "latest"
dotnet = "10.0.400"
go = "latest"
node = "24.19.0"
codex = "latest"
gh = "latest"
copilot = "latest"
rust = "latest"
viteplus = "latest"
"npm:playwright" = "latest"
poetry = "latest"
"dotnet:dotnet-ef" = "10.0.11"
"npm:@xai-official/grok" = "latest"
opencode = "latest"
claude = "latest"
pi = "latest"

[settings.upgrade]
auto_prune = false
