[tools]
bun = "latest"
dotnet = "10.0.400"
go = "latest"
node = "26.7.0"
codex = "latest"
gh = "latest"
copilot = "latest"
rust = "latest"
viteplus = "latest"
"npm:playwright" = "latest"
poetry = "latest"
"dotnet:dotnet-ef" = "10.0.11"
