- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: terminal setup
      import_tasks: playbooks/terminal_setup.yml
      become_user: fredrik

    - name: Turn of dash-to-dock
      community.general.dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed
        value: "false"
        state: present
      become_user: fredrik

    - name: Register custom keybindings
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
        value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom5/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom6/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom7/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom8/']"
        state: present
      become_user: fredrik

      #RADIX-TUI HOTKEY
    - name: Set open radix-tui keybinding name
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom3/name
        value: '"open radix-tui"'
        state: present
      become_user: fredrik

    - name: Set open radix-tui keybinding command
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom3/command
        value: '''popen radix-tui "/home/fredrik/.local/kitty.app/bin/kitty -e radix-tui --title radix-tui"'''
        state: present
      become_user: fredrik

    - name: Set open radix-tui keybinding binding
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom3/binding
        value: '"<Super>r"'
        state: present
      become_user: fredrik

      #ROFI HOTKEY
    - name: Set open program keybinding name
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom1/name
        value: '"Open program"'
        state: present
      become_user: fredrik

    - name: Set open program keybinding command
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom1/command
        value: '''rofi -show combi -modes combi -combi-modes "window,drun"'''
        state: present
      become_user: fredrik

    - name: Set open program keybinding binding
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom1/binding
        value: '"<Super>space"'
        state: present
      become_user: fredrik

      #TERMINAL HOTKEY
    - name: Set show terminal keybinding name
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom2/name
        value: '"Show terminal"'
        state: present
      become_user: fredrik

    - name: Set show terminal keybinding command
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom2/command
        value: '''popen main-terminal "/home/fredrik/.local/kitty.app/bin/kitty --title main-terminal"'''
        state: present
      become_user: fredrik

    - name: Set show terminal keybinding binding
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom2/binding
        value: '"<Super>Return"'
        state: present
      become_user: fredrik

      #RECORD GIF
    - name: Set record gif keybinding name
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom4/name
        value: '"Record gif"'
        state: present
      become_user: fredrik

    - name: Set record gif keybinding command
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom4/command
        value: '"peek -b ffmpeg"'
        state: present
      become_user: fredrik

    - name: Set record gif keybinding binding
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom4/binding
        value: '"<Shift>Print"'
        state: present
      become_user: fredrik

      #OPEN SLACK
    - name: Set open slack keybinding name
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom5/name
        value: '"Open slack"'
        state: present
      become_user: fredrik

    - name: Set open slack keybinding command
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom5/command
        value: '''popen Slack "flatpak run com.slack.Slack"'''
        state: present
      become_user: fredrik

    - name: Set open slack keybinding binding
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom5/binding
        value: '"<Super>s"'
        state: present
      become_user: fredrik

      #OPEN SUPERFILE
    - name: Set open superfile keybinding name
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom6/name
        value: '"Open superfile"'
        state: present
      become_user: fredrik

    - name: Set open superfile keybinding command
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom6/command
        value: '''popen superfile-tui "/home/fredrik/.local/kitty.app/bin/kitty --hold --title superfile-tui superfile"'''
        state: present
      become_user: fredrik

    - name: Set open superfile keybinding binding
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom6/binding
        value: '"<Super>f"'
        state: present
      become_user: fredrik

      #FLAMESHOT SCREENSHOT
    - name: flameshot keybinding name
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom7/name
        value: '"Take screenshot with flameshot"'
        state: present
      become_user: fredrik

    - name: flameshot keybinding command
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom7/command
        value: '"flameshot gui"'
        state: present
      become_user: fredrik

    - name: flameshot keybinding binding
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom7/binding
        value: '"Print"'
        state: present
      become_user: fredrik

      #OPEN TEAMs
    - name: Set open teams keybinding name
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom8/name
        value: '"Open teams"'
        state: present
      become_user: fredrik

    - name: Set open teams keybinding command
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom8/command
        value: '''popen "Microsoft Teams" "flatpak run com.github.IsmaelMartinez.teams_for_linux"'''
        state: present
      become_user: fredrik

    - name: Set open teams keybinding binding
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom8/binding
        value: '"<Super>t"'
        state: present
      become_user: fredrik

    - name: Copy ssh files
      copy:
        src: "{{playbook_dir}}/.ssh"
        dest: ~/
        owner: fredrik
        group: fredrik
        mode: 0700
      become_user: fredrik
