- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: flatpak setup
      import_tasks: playbooks/flatpak_setup.yml
      become_user: fredrik

    - name: go setup
      import_tasks: playbooks/go_setup.yml
      become_user: fredrik

    - name: terminal setup
      import_tasks: playbooks/terminal_setup.yml
      become_user: fredrik

    - name: copy ssh files
      copy:
        src: "{{playbook_dir}}/.ssh"
        dest: ~/
        owner: fredrik
        group: fredrik
      become_user: fredrik
