- hosts: localhost
  connection: local
  become: yes
  become_user: fredrik

  tasks:
    - name: pull dotfile repo
      git:
        repo: https://github.com/FredrikMWold/.dotfiles.git
        dest: ~/.dotfiles

    - name: install htop
      apt:
        name: htop
        state: latest
    - name: add vscode repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    - name: install vscode
      apt:
        name: code
        state: latest
    - name: install chrome
      apt:
        name: google-chrome-stable
        state: latest
    - name: install flameshot
      apt:
        name: flameshot
        state: latest
    - name: install stow
      apt:
        name: stow
        state: latest
    - name: debug
      shell: echo $HOME
    - name: install zsh
      apt:
        name: zsh
        state: latest
    - name: get oh-my-zsh status
      stat:
        path: ~/.oh-my-zsh
      register: oh_my_zsh_status
    - name: install oh-my-zsh
      shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      when: not oh_my_zsh_status.stat.exists
    - name: add flathub repository
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: install teams
      flatpak:
        name: com.github.IsmaelMartinez.teams_for_linux
        state: present
    - name: install slack
      flatpak:
        name: com.slack.Slack
        state: present
    - name: symlink dotfiles with stow
      shell: cd ~/.dotfiles && stow config
