- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: install htop
      apt:
        name: htop
        state: latest
    - name: add vscode repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    - name: install vscode
      apt:
        name: code
        state: latest
    - name: install chrome
      apt:
        name: google-chrome-stable
        state: latest
    - name: install flameshot
      apt:
        name: flameshot
        state: latest
    - name: add flathub repository
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: install teams
      flatpak:
        name: com.github.IsmaelMartinez.teams_for_linux
        state: present
