- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: terminal setup
      import_tasks: playbooks/terminal_setup.yml
      become_user: fredrik

    - name: Turn of dash-to-dock
      community.general.dconf:
        key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed
        value: "false"
        state: present
      become_user: fredrik

    - name: Register custom keybindings
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
        value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom3/']"
        state: present
      become_user: fredrik

    - name: Set open radix-tui keybinding name
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom3/name
        value: "'open radix-tui'"
        state: present
      become_user: fredrik

    - name: Set open radix-tui keybinding command
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom3/command
        value: '''zsh -c "export PATH="/home/fredrik/go/bin:$PATH"; wmctrl -a radix-tui || /home/fredrik/.local/kitty.app/bin/kitty -e radix-tui --title radix-tui"'''
        state: present
      become_user: fredrik

    - name: Set open radix-tui keybinding binding
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom3/binding
        value: "'<Super>r'"
        state: present
      become_user: fredrik

    - name: Set open program keybinding name
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom1/name
        value: "'Open program'"
        state: present
      become_user: fredrik

    - name: Set open program keybinding command
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom1/command
        value: '''rofi -show combi -modes combi -combi-modes "window,drun"'''
        state: present
      become_user: fredrik

    - name: Set open program keybinding binding
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom1/binding
        value: "'<Super>space'"
        state: present
      become_user: fredrik

    - name: Set show terminal keybinding name
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom2/name
        value: "'Show terminal'"
        state: present
      become_user: fredrik

    - name: Set show terminal keybinding command
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom2/command
        value: '''zsh -c "wmctrl -a main-teminal || /home/fredrik/.local/kitty.app/bin/kitty --title main-teminal"'''
        state: present
      become_user: fredrik

    - name: Set show terminal keybinding binding
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings:/custom2/binding
        value: "'<Super>Return'"
        state: present
      become_user: fredrik

    - name: Copy ssh files
      copy:
        src: "{{playbook_dir}}/.ssh"
        dest: ~/
        owner: fredrik
        group: fredrik
        mode: 0700
      become_user: fredrik
