- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: install htop
      apt:
        name: htop
        state: latest
    - name: add vscode repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    - name: install vscode
      apt:
        name: code
        state: latest
    - name: install chrome
      apt:
        name: google-chrome-stable
        state: latest
    - name: install flameshot
      apt:
        name: flameshot
        state: latest
    - name: install stow
      apt:
        name: stow
        state: latest
    - name: install zsh
      apt:
        name: zsh
        state: latest
    - name: install oh-my-zsh
      become_user: fredrik
      command: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - name: add flathub repository
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: install teams
      flatpak:
        name: com.github.IsmaelMartinez.teams_for_linux
        state: present
    - name: install slack
      flatpak:
        name: com.slack.Slack
        state: present
