# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia


# Window rule for floating terminal
windowrule {
  name = windowrule-2
  float = on
  size = 1200 800
  match:class = ^(floating-terminal)$
}


windowrule {
  name = windowrule-3
  float = on
  size = 1400 900
  match:class = teams-for-linux
}


windowrule {
  name = windowrule-4
  float = on
  size = 1400 900
  match:class = slack
}


windowrule {
  name = windowrule-5
  float = on
  size = 1400 900
  match:class = net-runelite-client-RuneLite
}


windowrule {
  name = windowrule-6
  float = on
  size = 1400 900
  match:class = com.stremio.stremio
}


windowrule {
  name = windowrule-7
  float = on
  size = 1400 900
  match:class = org.omarchy.radix-tui
}


windowrule {
  name = windowrule-8
  float = on
  size = 1400 900
  match:class = discord
}

windowrule {
  name = windowrule-9
  float = on
  move = ((monitor_w-window_w)/2-700) ((monitor_h-window_h)/2)
  match:class = vicinae
  match:title = ^Select files$
}

windowrule {
  name = windowrule-10
  float = on
  move = ((monitor_w-window_w)/2-700) ((monitor_h-window_h)/2)
  match:class = vicinae
  match:title = ^Open Directory$
}

windowrule = opacity 1.0 1.0, match:class .*
windowrule = size 1200 800, match:tag floating-window



source = /home/fredrik/.config/hypr/vicinae-monitors.conf

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
