- name: install go
  apt:
    name: golang-go
    state: latest

- name: install chrome
  apt:
    name: google-chrome-stable
    state: latest

- name: install vscodes
  apt:
    name: code
    state: latest

- name: install flameshot
  apt:
    name: flameshot
    state: latest

- name: install zsh
  apt:
    name: zsh
    state: latest

- name: install stow
  apt:
    name: stow
    state: latest

- name: install htop
  apt:
    name: htop
    state: latest

- name: install jq
  apt:
    name: jq
    state: latest

- name: install xclip
  apt:
    name: xclip
    state: latest

- name: install python3
  apt:
    name: python3
    state: latest

- name: install python3-pip
  apt:
    name: python3-pip
    state: latest
