- name: add flathub repository
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become_user: fredrik

- name: install teams
  flatpak:
    name: com.github.IsmaelMartinez.teams_for_linux
    state: present
  become_user: fredrik

- name: install slack
  flatpak:
    name: com.slack.Slack
    state: present
  become_user: fredrik

- name: install streamio
  flatpak:
    name: com.stremio.Stremio
    state: present
  become_user: fredrik

- name: install osrs
  flatpak:
    name: com.adamcake.Bolt
    state: present
  become_user: fredrik