- name: check if oh-my-zsh is installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh
  become_user: fredrik

- name: install oh-my-zsh
  shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc
  when: not oh_my_zsh.stat.exists
  become_user: fredrik

- name: remove old .zshrc
  file:
    path: ~/.zshrc
    state: absent
  become_user: fredrik

- name: clear font cache
  shell: fc-cache -f -v
  become_user: fredrik
